# Captive Portal entries parsed from CAPTIVE.md and LDF.md
# These entries ensure captive portal pages work correctly with WARP

locals {
  # Split Tunnel Exclusions (from CAPTIVE.md)
  # These domains will be excluded from the WARP tunnel to allow captive portal access
  captive_portal_split_tunnel_excludes = [
    { host = "*.aircanadawifi.com", description = "Air Canada captive portal" },
    { host = "*.alaskawifi.com", description = "Alaska captive portal" },
    { host = "*.aainflight.com", description = "American Air captive portal" },
    { host = "*.amtrakconnect.com", description = "Amtrak captive portal" },
    { host = "*.ana-inflight-wifi.com", description = "ANA captive portal" },
    { host = "*.login.attwifi.com", description = "AT&T captive portal" },
    { host = "*.mywifi.attwifi.com", description = "AT&T captive portal" },
    { host = "*.boingohotspot.net", description = "Boingo captive portal" },
    { host = "*.breezewifi.com", description = "Breeze captive portal" },
    { host = "*.airwayswifi.com", description = "captive portal" },
    { host = "*.itools.info", description = "captive portal" },
    { host = "*.jal-wifi.com", description = "captive portal" },
    { host = "*.login.yyc.com", description = "captive portal" },
    { host = "*.mywifi.io", description = "captive portal" },
    { host = "*.n438.network-auth.com", description = "captive portal" },
    { host = "*.neverssl.com", description = "captive portal" },
    { host = "*.rougewifi.com", description = "captive portal" },
    { host = "*.securewifilogin.com", description = "captive portal" },
    { host = "*.splash.skyadmin.io", description = "captive portal" },
    { host = "*.stage.edge.ihg.com", description = "captive portal" },
    { host = "*.venuewifi.com", description = "captive portal" },
    { host = "*.via.boingohotspot.net", description = "captive portal" },
    { host = "*.wifi.inflightinternet.com", description = "captive portal" },
    { host = "*.wifilauncher.com", description = "captive portal" },
    { host = "*.wifionboard.com", description = "captive portal" },
    { host = "*.wifi.cathaypacific.com", description = "Cathay Pacific captive portal" },
    { host = "*.deltawifi.com", description = "Delta captive portal" },
    { host = "*.wifi.delta.com", description = "Delta captive portal" },
    { host = "*.etihadwi-fly.com", description = "Etihad captive portal" },
    { host = "*.evawifi.com", description = "EVA captive portal" },
    { host = "*.globalsuite.net", description = "Globalsuite captive portal" },
    { host = "*.airborne.gogoinflight.com", description = "GoGo captive portal" },
    { host = "*.gogoinair.com", description = "GoGo captive portal" },
    { host = "*.gogoinflight.com", description = "GoGo captive portal" },
    { host = "*.icelandair.viasat.com", description = "Iceland Air captive portal" },
    { host = "*.icelandairwifi.com", description = "Iceland Air captive portal" },
    { host = "*.connect-edge.ihg.com", description = "IHG captive portal" },
    { host = "*.inflight-wifi.com", description = "Inflight captive portal" },
    { host = "*.inflightinternet.com", description = "Inflight captive portal" },
    { host = "*.flyfi.com", description = "JetBlue captive portal" },
    { host = "*.lufthansa-flynet.com", description = "Lufthansa captive portal" },
    { host = "*.norwegianwifi.com", description = "Norwegian captive portal" },
    { host = "*.southwestwifi.com", description = "Southwest captive portal" },
    { host = "*.unitedprivatescreening.com", description = "United captive portal" },
    { host = "*.unitedwifi.com", description = "United captive portal" },
    { host = "*.viasat.com", description = "Viasat captive portal" },
    { host = "*.viasat.io", description = "Viasat captive portal" },
    { host = "*.inflight.viasat.com", description = "ViaSat captive portal" },
    { host = "*.virgin-atlantic-wifi.com", description = "Virgin Atlantic captive portal" },
  ]

  # Local Domain Fallback entries (from LDF.md)
  # These domains will use the local DNS resolver instead of Cloudflare DNS
  captive_portal_local_domain_fallback = [
    { suffix = "aerlingus.com", description = "Aer Lingus captive portal" },
    { suffix = "aircanadawifi.com", description = "Air Canada captive portal" },
    { suffix = "rougewifi.com", description = "Air Canada captive portal" },
    { suffix = "aireuropa-ontheair.com", description = "Air Europa captive portal" },
    { suffix = "alaskawifi.com", description = "Alaska Air captive portal" },
    { suffix = "aainflight.com", description = "American Airlines captive portal" },
    { suffix = "amtrakconnect.com", description = "Amtrak captive portal" },
    { suffix = "ana-inflight-wifi.com", description = "ANA captive portal" },
    { suffix = "attwifi.com", description = "AT&T WiFi captive portal" },
    { suffix = "boingohotspot.net", description = "Boingo captive portal" },
    { suffix = "breezewifi.com", description = "Breeze captive portal" },
    { suffix = "cal-wifi.com", description = "CAL captive portal" },
    { suffix = "mywifi.io", description = "captive portal" },
    { suffix = "network-auth.com", description = "captive portal" },
    { suffix = "neverssl.com", description = "captive portal" },
    { suffix = "securewifilogin.com", description = "captive portal" },
    { suffix = "skyadmin.io", description = "captive portal" },
    { suffix = "venuewifi.com", description = "captive portal" },
    { suffix = "wifilauncher.com", description = "captive portal" },
    { suffix = "wifionboard.com", description = "captive portal" },
    { suffix = "deltawifi.com", description = "Delta captive portal" },
    { suffix = "etihadwi-fly.com", description = "Etihad captive portal" },
    { suffix = "evawifi.com", description = "Eva Air captive portal" },
    { suffix = "globalsuite.net", description = "GlobalSuite captive portal" },
    { suffix = "gogoinair.com", description = "GoGo captive portal" },
    { suffix = "gogoinflight.com", description = "GoGo captive portal" },
    { suffix = "icelandairwifi.com", description = "Iceland Air captive portal" },
    { suffix = "inflight-wifi.com", description = "Inflight captive portal" },
    { suffix = "inflightinternet.com", description = "Inflight captive portal" },
    { suffix = "jal-wifi.com", description = "JAL captive portal" },
    { suffix = "flyfi.com", description = "JetBlue captive portal" },
    { suffix = "lufthansa-flynet.com", description = "Lufthansa captive portal" },
    { suffix = "norwegianwifi.com", description = "Norwegian captive portal" },
    { suffix = "southwestwifi.com", description = "Southwest captive portal" },
    { suffix = "unitedprivatescreening.com", description = "United captive portal" },
    { suffix = "unitedwifi.com", description = "United captive portal" },
    { suffix = "wifigroundportal.united.com", description = "United captive portal" },
    { suffix = "viasat.com", description = "Viasat captive portal" },
    { suffix = "viasat.io", description = "Viasat captive portal" },
    { suffix = "virgin-atlantic-wifi.com", description = "Virgin Atlantic captive portal" },
  ]
}
